// Generated by Scripts/build-openssl-xcframeworks.sh - do not edit.
// Forwards libssh2's canonical <openssl/...> include into OpenSSLCrypto.framework,
// whose headers live under swiftsftp_openssl/ so they cannot collide with another
// SDK's openssl/ tree. See the Stage 4 note in that script.
#pragma once
#include <OpenSSLCrypto/swiftsftp_openssl/idea.h>
